/* Report counts and human visual review; no generated or inferred grades. */
(() => {
 'use strict';
 const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 window.fidelityHTML = stage => {
  const data = window.WORLD_FIDELITY;
  if (!data) return '<p>Report-to-render comparison is unavailable.</p>';
  const targets = data.targets.filter(t => t.id === stage || (data.being_stages[t.id] || []).includes(stage));
  const table = target => `<details class="fidelity-target" ${target.id === stage ? 'open' : ''}><summary>${esc(target.id)} · ${(target.coverage * 100).toFixed(1)}% reviewed coverage · ${target.passed ? 'PASS' : 'NOT PASSED'}</summary><p><strong>${esc(target.basis)}</strong>. ${target.reports.toLocaleString()} counted reports; ${target.passages.toLocaleString()} candidate passages. Passage review: ${target.passage_audit.included_reports} included / ${target.passage_audit.excluded_reports} excluded. Raw matches can include ordinary settings or another trip phase; unvalidated counts cannot pass fidelity. Counts are not population prevalence.</p><div class="fidelity-scroll" tabindex="0" role="region" aria-label="${esc(target.id)} report and render comparison"><table class="fidelity-table"><caption>What reports say / what the render shows</caption><thead><tr><th scope="col">Descriptor / reports</th><th scope="col">Render comparison</th></tr></thead><tbody>${target.descriptors.map(d => `<tr><th scope="row">${esc(d.descriptor)}<br><small>${d.count.toLocaleString()} · ${(d.fraction * 100).toFixed(1)}%</small><br>${d.report_links.map(r => `<a href="https://www.reddit.com/r/${encodeURIComponent(r.sub)}/comments/${encodeURIComponent(r.id)}/" target="_blank" rel="noopener noreferrer">${esc(r.id)}</a>`).join(' ')}</th><td><strong>${esc(d.grade)}</strong><br>${esc(d.observation)}</td></tr>`).join('')}</tbody></table></div></details>`;
  const audit = data.route_audit;
  // REMOVED 2026-09-11 (HANDOFF.md D12): the per-target RECOGNISE / CLOSE / GAME craft
  // log lived here and rendered into the visitor drawer - 19 targets, GAME x50, with the
  // build agent's turn notes ("four-turn budget exhausted", "await the driver for void").
  // Dwayne retired that scale in REDIRECT5: recognition is corroboration, never a gate, so
  // presenting it to readers as a fidelity verdict published a claim already withdrawn.
  // Still in git history; the report-vs-render tables below are unaffected and remain.
  const realismHTML = '';
  return `<section class="fidelity"><h3>Reports compared with this scene</h3><p>Descriptor coverage: <strong>${data.passed ? 'reviewed' : 'not yet fully reviewed'}</strong>. UNREVIEWED means no inspected render grade, not an observed absence. Score weights: present 1, partial ½, absent 0; target ≥80%, with no missing top-ten descriptor.</p><p>These are local word-family tallies from all 14,309 tagged reports. Nearby text may describe a different moment, a metaphor or a nonvisual feeling. Counts and render judgments are separate; this cannot certify a subjective experience.</p>${realismHTML}${targets.map(table).join('')}<details><summary>Route order and timing comparison</summary><p>${esc(audit.limitations)}</p><ul>${audit.departures.map(d => `<li>${esc(d)}</li>`).join('')}</ul><p>Configured passage time: ${audit.configured_seconds} seconds plus transitions; an editorial pace, not measured experience duration. Route review: ${data.route_passed ? 'PASS' : 'PENDING'}.</p><div class="fidelity-scroll" tabindex="0" role="region" aria-label="Route mention counts"><table class="fidelity-table"><caption>Adjacent phase mentions, forward / reverse</caption><thead><tr><th scope="col">Route edge</th><th scope="col">Reports' mentions</th></tr></thead><tbody>${audit.edges.map(e => `<tr><th scope="row">${esc(e.from)} → ${esc(e.to)}</th><td>${e.shared_phase ? 'same phase' : `${e.forward} / ${e.reverse}`}</td></tr>`).join('')}</tbody></table></div></details></section>`;
 };
})();
