"""Validate every room spec, then emit what the page can actually load.

The walkthrough is opened over file:// by both harnesses, where fetch() of a sibling file is
blocked by CORS. So specs and grammar ship as <script> payloads the way data.js does, not as
JSON the page fetches. This is the only step that writes them, and it refuses to write
anything if a single spec fails validation - a room that cannot be justified never reaches
the page in the first place.

    python build_rooms.py            validate all, emit primitives.js + rooms.js
    python build_rooms.py --check    validate only, write nothing
"""
import argparse
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from validate import primitives, atlas_keys, check  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='validate only, emit nothing')
    a = ap.parse_args()

    grammar, keys = primitives(), atlas_keys()
    specs, bad = {}, 0
    for path in sorted((HERE / 'rooms').glob('*.json')):
        problems = check(path, grammar, keys)
        if problems:
            bad += 1
            print('%s: %d problem(s)' % (path.name, len(problems)))
            for p in problems:
                print('   -', p)
            continue
        spec = json.loads(path.read_text(encoding='utf-8'))
        if spec['id'] in specs:
            bad += 1
            print('%s: duplicate room id %r' % (path.name, spec['id']))
            continue
        specs[spec['id']] = spec
        cited = len({e['cites'] for e in spec['elements']})
        print('%-18s %2d elements, %d distinct citations, valid'
              % (spec['id'], len(spec['elements']), cited))

    if bad:
        print('\n%d spec(s) failed; nothing written.' % bad)
        raise SystemExit(1)
    if a.check:
        print('\n%d room(s) valid; --check, nothing written.' % len(specs))
        raise SystemExit(0)

    (HERE / 'primitives.json').write_text(json.dumps(grammar, indent=2), encoding='utf-8')
    (HERE / 'primitives.js').write_text(
        '// GENERATED by engine/build_rooms.py from fractal.js - do not hand-edit.\n'
        '// The compiler needs each primitive\'s real arity; parsing it from the engine means\n'
        '// the grammar cannot drift from the code it describes.\n'
        'window.RoomPrimitives=' + json.dumps(grammar, separators=(',', ':')) + ';\n',
        encoding='utf-8')
    (HERE / 'rooms.js').write_text(
        '// GENERATED by engine/build_rooms.py - do not hand-edit. Source: engine/rooms/*.json\n'
        '// Every element in every spec resolved to a real atlas node before this was written.\n'
        'window.RoomSpecs=' + json.dumps(specs, ensure_ascii=False, separators=(',', ':')) + ';\n',
        encoding='utf-8')
    print('\nwrote primitives.js (%d primitives) and rooms.js (%d rooms)'
          % (len(grammar), len(specs)))


if __name__ == '__main__':
    main()
